# Generated by Django 5.1.3 on 2024-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_right',
            field=models.BooleanField(default=True),
        ),
    ]
