# Generated by Django 5.1.3 on 2025-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='challenge_scores',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
